[package]
name = "sdk"
version = "0.6.93"
edition = "2021"
license = "Apache-2.0"


[dependencies]
async-trait = "0.1.85"
futures = "0.3.31"
futures-util = "0.3.31"
iggy = {version = "0.6"}
tracing = { version = "0.1.41" }
tokio = "1.43.0"
tokio-util = "0.7.13"
